config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticated :user do
    root "works#index", as: :authenticated_root
  end
  root "home#index"

  get "disclaimer", to: "home#disclaimer", as: "disclaimer"
  get "policy", to: "home#policy", as: "policy"
  get "contact", to: "home#contact", as: "contact"

  resources :works, only: %i[index show new create destroy]
  resources :notifications, only: :show
  resource :notifications, only: :update # `PATCH /notifications`でBulk Update
  resource :order, only: :show

  namespace :admin do
    resource :dashboard, only: :show
  end

  devise_for :users
  get "sitemap", to: redirect("#{Rails.application.credentials.s3_cdn_url}/sitemaps/sitemap.xml.gz")
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  default_form_builder ApplicationFormBuilder

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  before_action :redirect_to_original_domain, if: %i[herokuapp_domain? production?]

  helper_method :notifications, :notifications_count, :notifications_exists?

  private

  def redirect_to_original_domain
    redirect_to "https://#{Settings.original_domain}#{request.fullpath}", status: 301
  end

  def herokuapp_domain?
    request.domain == Settings.herokuapp_domain
  end

  def production?
    Rails.env.production?
  end

  def not_authorized
    redirect_to root_path, alert: "権限がありません。"
  end

  def notifications
    @notifications ||= current_user.notifications.unread.preload(work: :trained_model).order(created_at: :desc)
  end

  def notifications_count
    @notifications_count ||= notifications.count
  end

  def notifications_exists?
    notifications_count > 0
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def display_meta_tags_default
    display_meta_tags(
      site: "リアルバーチャルYoutuber",
      separator: "|",
      reverse: true,
    )
  end

  def icon(*classes)
    tag.i(class: classes.join(" "))
  end

  def smartphone?
    browser.device.mobile?
  end

  def tablet_pc?
    !!smartphone?
  end

  def ago(time)
    TimeDifference.ago(time)
  end

  def ago_if_datetime(val)
    val.is_a?(Time) ? ago(val) : val
  end

  def render_navbar
    login_page            = current_page?(controller: "devise/sessions",      action: "new")
    signup_page           = current_page?(controller: "devise/registrations", action: "new")
    forgot_password_page  = current_page?(controller: "devise/passwords",     action: "new")
    change_password_page  = current_page?(controller: "devise/passwords",     action: "edit")

    if login_page || signup_page || forgot_password_page || change_password_page
      render "unobtrusive_navbar"
    else
      render "navbar"
    end
  end

  def h1(title)
    content_for(:h1, title)
  end

  def h1_text_only(title)
    content_for(:h1_text_only, title)
  end

  def z_depth_0_if_h1
    "z-depth-0" if content_for?(:h1) || content_for?(:h1_text_only)
  end
end

app/views/application/_flash_message.html.haml
- if notice
  .alert.alert-primary!= notice
- if alert
  .alert.alert-danger!= alert

app/views/application/_footer.html.haml
%footer.page-footer.font-small.stylish-color-dark.pt-3.mt-50px.sticky-bottom
  %ul.list-unstyled.list-inline.text-center
    %li.list-inline-item
      = link_to "お問い合わせ", contact_path, class: %i[btn btn-outline-default waves-effect font-weight-bold]
    %li.list-inline-item
      = link_to Settings.twitter_url, class: %i[btn-floating btn-tw mx-1], target: "_blank" do
        = icon("fab", "fa-twitter")
    %li.list-inline-item
      = link_to Settings.github_url, class: %i[btn-floating btn-reddit mx-1], target: "_blank" do
        = icon("fab", "fa-github")

  .footer-copyright.text-center.py-3.font-75
    %span.mx-1 ©shita1112 2019
    %a.mx-1= link_to "プライバシーポリシー", policy_path
    %a.mx-1= link_to "免責事項", disclaimer_path

app/views/application/_h1.html.haml
- case
- when content_for?(:h1)
  .h1-bg-color.white-text.z-depth-1
    .container
      %h1.h2-responsive.my-3= yield :h1
- when content_for?(:h1_text_only)
  .h1-bg-color.white-text.z-depth-1
    .text-only
      %h1.h2-responsive.my-3= yield :h1_text_only

app/views/application/_navbar.html.haml
%header
  %nav.navbar{class: z_depth_0_if_h1}
    .container.p-0-if-smartphone
      = link_to root_path, class: "navbar-brand mr-0" do
        = image_tag "inversed_logo.png", alt: "ロゴ"

      .text-right
        - if user_signed_in?
          = link_to "動画作成", new_work_path, class: "btn btn-outline-primary waves-effect font-weight-bold btn-xs-if-smartphone z-depth-0", role: "button"

          .dropdown.d-inline-block
            %button.dropdown-toggle.btn-floating.btn-floating-border.waves-effect.btn-sm{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}= icon("fas", "fa-user")
            .dropdown-menu.dropdown-menu-right
              = link_to "高品質な動画を作る・顔を作る", order_path, class: "dropdown-item"
              .dropdown-divider
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item"
              - if current_user.admin?
                .dropdown-divider
                = link_to "ダッシュボード", admin_dashboard_path, class: "dropdown-item"

          = render "notifications/notifications"
        - else
          = link_to "ログイン", new_user_session_path, class: "btn btn-outline-primary waves-effect font-weight-bold btn-xs-if-smartphone z-depth-0", role: "button"
          = link_to "ユーザー登録", new_registration_path(:user), class: "btn btn-primary waves-effect font-weight-bold btn-xs-if-smartphone z-depth-0", role: "button"

app/views/application/_unobtrusive_navbar.html.haml
%header.mb-3
  %nav.navbar
    .container.p-0-if-smartphone
      = link_to root_path, class: "navbar-brand mr-0" do
        = image_tag "inversed_logo.png", alt: "ロゴ"